version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: project3a
    container_name: flask-project3a
    ports:
      - "5003:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1